# Generated by Django 4.2.3 on 2023-08-01 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeMainIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.mainingredient')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.recipe')),
            ],
        ),
    ]
