# Generated by Django 4.2.3 on 2023-08-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_cuisine_cuisine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.TextField(default='https://thehalalworld.com/uploads/pages/Sardine-tea-sandwiches.jpg'),
        ),
    ]
