# Generated by Django 4.2.3 on 2023-08-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemainingredient',
            name='main_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipemainingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipepreptimes',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipepreptimes',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetypes',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetypes',
            name='type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_main_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.mainingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_prep_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.preptime'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.type'),
        ),
        migrations.DeleteModel(
            name='RecipeCuisine',
        ),
        migrations.DeleteModel(
            name='RecipeMainIngredient',
        ),
        migrations.DeleteModel(
            name='RecipePrepTimes',
        ),
        migrations.DeleteModel(
            name='RecipeTypes',
        ),
    ]
