# Generated by Django 4.2.3 on 2023-08-07 15:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0014_remove_recipemainingredient_main_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ('cuisine_name',)},
        ),
        migrations.AlterModelOptions(
            name='mainingredient',
            options={'ordering': ('ingredient_name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('type_name',)},
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
