# Generated by Django 4.2.3 on 2023-08-01 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_type_recipetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prep_time', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePrepTimes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prep_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.preptime')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
